### PR TITLE
Update auth.md

### PR DESCRIPTION
**Pull request by c-git**
Fix typo an to a as next word starts with a consonant

### CODE REVIEW

**Comment by giraffate** [comment]
@c-git Sorry to keep you waiting. If you can resolve conflicts, we're ready to merge this.

**Comment by c-git** [comment]
Ok will do

**Comment by c-git** [comment]
Close in error when I updated the branch, reopened.

Should be fine now, let me know if there is anything else you need me to do.

**Review by giraffate — APPROVED** [review]
Thanks!

**Pull request merged**
