### PR TITLE
Add axum to home page

### PR DESCRIPTION
**Pull request by 3olkin**

### CODE REVIEW

**Comment by ibraheemdev** [comment]
The point isn't to list all framework on the home page, axum is still very new, and actix-web, rocket, tide, and warp are by far the most popular/mature.

**Comment by ibraheemdev** [comment]
I think I'll leave this out for now.

**Comment by ibraheemdev** [comment]
Oops, didn't mean to merge :see_no_evil:

**Comment by randomairborne** [comment]
Axum has now almost caught up to Actix, has beaten Tide, and has blown away Warp and Rocket
.

**Comment by ibraheemdev** [comment]
@randomairborne I agree, I'd accept a pull request now, likely removing Warp (as even the creator agrees Axum is a more general option).

**Pull request merged**
