### PR TITLE
update third party services topic

### PR DESCRIPTION
**Pull request by ibraheemdev**
Add aws and azure sdk's, new official elastic search client, meilisearch client and change `level` from 5 to 4

### CODE REVIEW

**Comment by ibaryshnikov** [comment]
Looks good. Is `.json` for `tantivy` missing?

**Comment by ibraheemdev** [comment]
Oh yeah, I was wondering if `tantivy` should even be added?

**Comment by ibaryshnikov** [comment]
For sure, it's an interesting library. Though it feels hard to decide on a category.

**Comment by ibraheemdev** [comment]
Well, the description is `full-text **search** engine library`. So I guess search makes the most sense. I'm not sure if it's a "third-party service" though...

**Comment by ibaryshnikov** [comment]
> I'm not sure if it's a "third-party service" though...

That's what I mean. I think it's good as is, but if there are a lot of such libraries, it will be possible to create a `building blocks` category.

**Comment by ibaryshnikov** [comment]
Thanks!

**Pull request merged**
