### PR TITLE
rustfbp is the basic component of fractalide - simple rust microservices

### PR DESCRIPTION
**Pull request by sjmackenzie**

### CODE REVIEW

**Comment by gnunicorn** [comment]
Hello @sjmackenzie,

thanks for the addition. I was trying to understand what fractalide is and how this relates to rust+web and helps people built websites/services. Could you maybe shed some light into these questions, I couldn't really get answers that were satisfying...

**Comment by sjmackenzie** [comment]
Well, Fractalide is does distributed computing, the latest fad is this silly thing called `microservices`.
Now I saw how your code worked and noticed it only seemed to accept cargo crates. Hence only `rustfbp` the lowest level "thing" associated with Fractalide can be put in there. Ideally a simple link to Fractalide would do.

**Comment by sjmackenzie** [comment]
The easiest way to convey the information was to change the description of rustfbp to be "Rustfbp provides a simple, composable, clearly defined API, with a C ABI for every component within a Fractalide microservice deployment." This way, you can keep the same technique of simply listing the crate name, and the explanation will come through on your website.

**Comment by sjmackenzie** [comment]
@gnunicorn

**Comment by gnunicorn** [comment]
thanks, @sjmackenzie . No need to mention me, I get all the post immediately ;) .

Thanks for the explanation. I (kinda) understand what rustbp does, but I still haven't fully understood what fractalide itself is/does. Is it meant for distributed computing - as in clusters in a data center? Or more like peer-2-peer framework like maidsafe's SAFE network? Is this basically a deployment system? What would a web-developer do/use the rustfbp library for? What would they want to achieve?

I just [pushed a new website feature](https://github.com/bashyHQ/arewewebyet/commit/40be9b2448981bd2530f8371c63368decddf1a71 to also track/link to features that aren't yet on crates.io but we'd like to point people to. 

Thanks for the info!

**Comment by sjmackenzie** [comment]
viz: new website feature, this is great, I'll refactor my PR.

Okay, it seems I'm really having problems conveying what fractalide is! Your feedback is greatly appreciated.

Yes fractalide is for distributed computing, it can work in clusters or datacenters, it is not an open internet peer-2-peer protocol, (I have plans up my sleeve for that later, which will be layer on fractalide) It is _also_ a code deployment system, (and supports continuous integration too) because in a big cluster of machines it can become annoying keeping track of all those moving pieces with their associated versions of each component. This system is meant to remove as many classes of errors as possible. 

When you say a web developer, I'm presuming web developers do develop backends? My goal is to make a lovely high performance backend that allows an HTML CSS Javascript programmer who's never seen rust be able to compose a server backend by connecting boxes and lines. In other words they don't even look at rust code but at stuff like this: https://github.com/fractalide/fractal_workbench/blob/master/components/workbench/default.nix#L17-L21

Later it'll become more beautiful and functional.

**Comment by gnunicorn** [comment]
Ok. Still not 100% about the relation to rust-web, but I just wait for your next PR and see then. Thanks for explanations!

Closing until then :) .

**Comment by sjmackenzie** [comment]
It's really quite simple...
to have a website you need a server, I think we can both agree to that
right? Most servers nowadays are designed to run on one box - putting it as
simple as possible.
This system just allows your to do computation in a distributed
environment, so it's still a server.
Therefore there is strong relation to "rust-web" because this _is_ a
server, but a distributed server.

I hope that makes it clearer.

**Pull request closed without merging**
