### PR TITLE
Fix broken config file

### PR DESCRIPTION
**Pull request by adriantombu**
When trying to run the site locally with `zola serve` we have the following error:

```bash
> zola -V
zola 0.19.1

> zola serve
Error: Failed to serve the site
Error: TOML parse error at line 9, column 1
  |
9 | highlight_code = false
  | ^^^^^^^^^^^^^^
unknown field `highlight_code`, expected one of `base_url`, `theme`, `title`, `description`, `default_language`, `languages`, `translations`, `generate_feeds`, `feed_limit`, `feed_filenames`, `hard_link_static`, `taxonomies`, `author`, `compile_sass`, `minify_html`, `build_search_index`, `ignored_content`, `ignored_static`, `mode`, `output_dir`, `preserve_dotfiles_in_output`, `link_checker`, `slugify`, `search`, `markdown`, `extra`
```

This PR fixes this problem by moving the `highlight_code` key under the `[markdown]` section in  `config.toml` as seen in the [zola configuration doc](https://www.getzola.org/documentation/getting-started/configuration/).

### CODE REVIEW

**Comment by LukeMathWalker** [comment]
This is not a bug, unless we bump up the version of `zola` used to render the website (see [here](https://github.com/rust-lang/arewewebyet/blob/1ff1a19ccd9e41d673da5c69fdf1f5ad40e776f9/.github/workflows/zola.yml#L16)), which would indeed be desirable!

**Comment by LukeMathWalker** [comment]
I.e. merging this without updating the deployment pipeline would break it.

**Comment by adriantombu** [comment]
Woopsie, silly me 🙈 I also upgraded the GA dependencies at the same time

**Comment by LukeMathWalker** [comment]
[It worked ✅](https://github.com/rust-lang/arewewebyet/actions/runs/10036722730/job/27735026308)!

**Pull request merged**
