### PR TITLE
Update iron to include the new homepage

### PR DESCRIPTION
**Pull request by ohsayan**
## Description
Added the homepage that includes both documentation and other important updates for ironframework

## Motivation and Context
The homepage is a great starting point for developers

## How Has This Been Tested?
Not tested yet

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/rust-net-web/tide/blob/master/.github/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by ohsayan** [comment]
Should I be **minfiying** the _json_ for jekyll?

**Comment by yoshuawuyts** [comment]
@sntdevco yeah, having the blob be minified would be much appreciated!

**Comment by sntdevco** [comment]
> @sntdevco yeah, having the blob be minified would be much appreciated!

Done, review the current commit

**Comment by ohsayan** [comment]
> @yoshuawuyts  yeah, having the blob be minified would be much appreciated!

Done, review the current commit

**Review by yoshuawuyts — APPROVED** [review]

**Pull request merged**
