### PR TITLE
Zola Rewrite

### PR DESCRIPTION
**Pull request by ibraheemdev**
The migration is complete! The only changes are the removal of comments, and the removal of the comments, the removal of the `last_updated` footer because zola doesn't provide a `site.time` variable, and the date format change. I'll see if I can get this deployed to a gh-pages site.

References: #107

### CODE REVIEW

**Comment by ibraheemdev** [comment]
I got the github action going [and published here!](https://ibraheemdev.github.io/arewewebyet/) This can be merged and deployed by changing the `base_url` in the `config.toml`, and generating the secret token with the name `ZOLA_TOKEN`. See [the guide here](https://www.getzola.org/documentation/deployment/github-pages/)

**Comment by ibaryshnikov** [comment]
@ibraheemdev thanks for your great work, that's a huge improvement! I'll try to find time to review it on the weekend. Meanwhile, are there any instructions to build the site locally?

**Comment by ibraheemdev** [comment]
You can just clone the repo and run `zola serve`. The [zola installation guide is here](https://www.getzola.org/documentation/getting-started/installation/)

**Comment by ibraheemdev** [comment]
@ibaryshnikov Also, the web-presence-team said that a maintainer of the repo had to ask them for permission to add a new maintainer. Any chance you could do that for me?

**Comment by ibraheemdev** [comment]
Deployment will require generating a token with repo access and updating the gh-pages build branch. That will require someone with access to the repo settings, which might be an issue.

**Comment by ibraheemdev** [comment]
I got the github workflow going with the built in `GITHUB_TOKEN` and [peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages), and manually installing the zola binary. Should I fix the conflicts and merge this?

**Pull request merged**
