### PR TITLE
Remove Iron as it is no longer maintained

### LINKED ISSUE #102: Iron is dead. It should be pulled from the active list.
As of https://github.com/iron/iron/commit/9e5bccb407b1ec8daef51b0d7494627e5c5fc307 Iron was marked inactive. It's probably not best to point users to frameworks that are overtly inactive.

### PR DESCRIPTION
**Pull request by wiktor-k**
Fixes #102

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Comment by wiktor-k** [comment]
Hello, is there anything to be done to get this merged?

**Comment by radix** [comment]
Sorry about the delay!

**Comment by wiktor-k** [comment]
No problem, thanks.

**Comment by robertohuertasm** [comment]
There's still a mention to `Iron` in https://github.com/bashyHQ/arewewebyet/blob/gh-pages/topics/frameworks.md

**Comment by radix** [comment]
@robertohuertasm I realize that. I'm not sure if it's the right time to completely remove it from the frameworks list; this PR simply removed it from the "recommended frameworks".

I also have a PR outstanding (#112)  that removes the recommendation to look at an Iron-based example app on the front page (for two reasons: because it's Iron-based, and because it doesn't seem to exist any more).

**Comment by robertohuertasm** [comment]
@radix, I understand your concern. I just read the [latest comment](https://github.com/iron/iron/commit/9e5bccb407b1ec8daef51b0d7494627e5c5fc307#commitcomment-28205769) (35 mins ago) from the Iron owner (@untitaker) and it seemed to me that `Iron` has come to its end. At least, they strongly recommend to fork it instead of continuing its development.

**Pull request merged**
