### PR TITLE
Rewrite in Zola (WIP)

### PR DESCRIPTION
**Pull request by ibraheemdev**
This is a work in progress rewrite of the site in Zola. Therd have been no issues so far and it is going smooth!

References #107

### CODE REVIEW

**Comment by ibraheemdev** [comment]
One weird issue just popped up when writing the topic level indicator shortcode (partial). Fixed with a little whitespace hack. Opened a ticket in getzola/zola#1203

**Comment by ibraheemdev** [comment]
There is another issue with regards to the comments data. Zola has no way of checking if a file exists, meaning that if you call `load_data` on a non existent file, the build fails. This gives us two options. Scaffold empty .yml files for each package, or remove the comment section entirely.

**Comment by ibaryshnikov** [comment]
The comment section is barely used so far, no much harm in removing it.

**Comment by ibraheemdev** [comment]
The migration is complete! The only changes are the removal of comments, and the removal of the comments, the removal of the `last_updated` footer because zola doesn't provide a `site.time` variable, and the date format change. I'll see if I can get this deployed to a gh-pages site.

**Comment by ibraheemdev** [comment]
Opening a new issue because the `zola` branch had to be merged into master to create the gh-pages action

**Pull request closed without merging**
